version: "3.9"
services:
ollama:
image: ollama/ollama:latest
container_name: ollama
ports:
- "11434:11434"
volumes:
- ollama:/root/.ollama
restart: unless-stopped
chroma:
image: chromadb/chroma:latest
container_name: chroma
ports:
- "8000:8000"
volumes:
- chroma:/chroma/chroma
restart: unless-stopped
streamlit:
build:
context: .
dockerfile: Dockerfile.streamlit
container_name: streamlit
ports:
- "8501:8501"
volumes:
- ./src:/app/src
- ./data:/app/data
- ./db:/app/db
depends_on:
- ollama
- chroma
env_file:
- .env
restart: unless-stopped
volumes:
ollama:
chroma:
